// Copyright 2021 The Terasology Foundation
// SPDX-License-Identifier: Apache-2.0
package org.terasology.weatherManager.systems;

import org.terasology.weatherManager.weather.ConditionAndDuration;

/**
 * Factory class for creating changing weather conditions Created by Linus on 5-11-2014.
 */
public interface WeatherConditionProvider {

    String toDisplayString();

    /**
     * Gets the next {@link ConditionAndDuration} generated by this provider
     *
     * @return WeatherCondition and duration generated by this provider
     */
    ConditionAndDuration getNext();

}
