/*
 * Copyright 2014 MovingBlocks
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.terasology.weatherManager.systems;

import org.terasology.weatherManager.weather.ConditionAndDuration;

/**
 * Factory class for creating changing weather conditions
 * Created by Linus on 5-11-2014.
 */
public interface WeatherConditionProvider {

    String toDisplayString();

    /**
     * Gets the next {@link ConditionAndDuration} generated by this provider
     * @return WeatherCondition and duration generated by this provider
     */
    ConditionAndDuration getNext();

}
